# Generated by Django 4.2.8 on 2024-02-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('department', models.CharField(choices=[('commerce', 'Commerce'), ('science', 'Science'), ('arts', 'Arts')], max_length=50)),
                ('course', models.CharField(choices=[('bba', 'BBA'), ('bcom', 'BCom'), ('bca', 'BCA'), ('bsc', 'BSc'), ('ba', 'BA')], max_length=50)),
                ('purpose', models.CharField(choices=[('enquiry', 'Enquiry'), ('place_order', 'Place Order'), ('return', 'Return')], max_length=50)),
                ('materials_provide', models.ManyToManyField(to='schoolapp.material')),
            ],
        ),
    ]
