# Generated by Django 4.2.8 on 2023-12-11 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='services',
            new_name='places',
        ),
    ]
